// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0rHmLl7CEloA2Hj8BXiD2lbAIzPcrPo',
    appId: '1:774197971599:web:6392db3cbc850ff5623efa',
    messagingSenderId: '774197971599',
    projectId: 'jspm-pulse-95848',
    authDomain: 'jspm-pulse-95848.firebaseapp.com',
    storageBucket: 'jspm-pulse-95848.firebasestorage.app',
    measurementId: 'G-Z77PWYVSB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB57lSJKJt5rX_N_61xnS1PMTzucgFLiS8',
    appId: '1:774197971599:android:6ceff31389f185e4623efa',
    messagingSenderId: '774197971599',
    projectId: 'jspm-pulse-95848',
    storageBucket: 'jspm-pulse-95848.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs0HWXkqq9fZW0GWLK2q9Aj-zQnN-Lh5w',
    appId: '1:774197971599:ios:378ec77cfad01bad623efa',
    messagingSenderId: '774197971599',
    projectId: 'jspm-pulse-95848',
    storageBucket: 'jspm-pulse-95848.firebasestorage.app',
    iosBundleId: 'com.example.jspmPulse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs0HWXkqq9fZW0GWLK2q9Aj-zQnN-Lh5w',
    appId: '1:774197971599:ios:378ec77cfad01bad623efa',
    messagingSenderId: '774197971599',
    projectId: 'jspm-pulse-95848',
    storageBucket: 'jspm-pulse-95848.firebasestorage.app',
    iosBundleId: 'com.example.jspmPulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP0rHmLl7CEloA2Hj8BXiD2lbAIzPcrPo',
    appId: '1:774197971599:web:8ca5ed2b910d038f623efa',
    messagingSenderId: '774197971599',
    projectId: 'jspm-pulse-95848',
    authDomain: 'jspm-pulse-95848.firebaseapp.com',
    storageBucket: 'jspm-pulse-95848.firebasestorage.app',
    measurementId: 'G-ZW4F663KLD',
  );

}